# Configurations
title:            Programación Avanzada 
longtitle:        Programación Avanzada 
author:           Flavio D Colavecchia
email:            fcolavecchia@gmail.com
description: >
  Un curso de programación avanzada con estilo funcional

version:          1.0
gitbook_version:  3.2.3

url:              'https://IBProgramacionAvanzada.github.io'
# baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: github

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  fsharp:
    output: true
    permalink: /:collection/:path/
    order:
      - 00_Intro.md
      - 01_Fundamentals_new.md
      - 02_Functions_new.md
      - 03_Exercises.md
      - 10_MasSobreFunciones.md    
      - 11_IntroToTypes_es.md        
      - 12_DiscriminatedUnions_es.md 
      - 13_Records_es.md
      - 14_Exercises.md
      - 20_ControlFlow.md      
      - 21_Exercises.md 
      - 30_Tuples.md
      - 31_OnCollections.md 
      - 33_Exercises.md
      - 40_MoreOnCollections.md
      - 41_Maps.md
      - 42_Exceptions.md
      - 43_Exercises.md
      - 50_Results.md
      - 51_Units.md 
      - 53_Exercises.md
      - 60_YetAnotherTakeOnCollections.md
      - 61_IO.md
      - 63_Exercises.md 
      - 70_VendingMachineReadFood.md
      - 73_Exercises.md 
      - 80_TypeProviders.md
      - 83_Exercises.md 
      - 90_Dotnet.md
      - 999_resources.md 


page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
